{
 "title": "New dashboard",
 "description": "shell-log-adding",
 "time": { "from": "2025-06-02T17:07:08.868Z", "to": "2025-06-04T17:07:08.868Z" },
 "panels": [
  {
   "title": "Resident-Memory",
   "type": "gauge",
   "description": "Memory-resident",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "cpu-total-seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(go_cpu_classes_total_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx-Log",
   "type": "logs",
   "description": "about-WEB-GET-POST",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"nginx\"}"
    }
   ]
  },
  {
   "title": "Docker-Logs",
   "type": "logs",
   "description": "the log inside container",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"dockerlogs\"}"
    }
   ]
  },
  {
   "title": "Shell-Log",
   "type": "logs",
   "description": "the point",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"shell\"}"
    }
   ]
  }
 ]
}